### ISSUE TITLE
Show out of data message

### ISSUE THREAD

**Issue by astopy** [zooniverse/mobile#131]
At the moment there's no indication when a project's mobile workflow is complete, other than the user getting lots of already seens.

**Comment by noahmalmed** [comment]
@beckyrother I think I will need some design decisions from you to move forward with this one

**Comment by noahmalmed** [comment]
This will go in as a part of the projects page redesign

**Comment by beckyrother** [comment]
Here's an image showing the banner for on the projects screen.
![zooniverse-app-2018_sketch](https://user-images.githubusercontent.com/1392130/36284077-0d327f10-126c-11e8-9567-29d875f31219.png)

And here's a link to the InVision prototype: https://invis.io/AJFVUMPNV9R#/279688121_Projects_-_Nature

Couple of things going on in InVision: 
- sorting by mobile first (great idea Noah)
- updated project card to match project cards on the (not-logged-in) home page
- added the category name to the header bar
- changed the arrows on projects with multiple workflows to a simple caret (>) rather than the colored circle. this is not a change we talked about but i don't like the different colored circles; this streamlines the app and keeps the focus on the text rather than wondering about why the circles are different colors. in invision > inspect, you can switch to the Assets tab to download it (or use fontawesome `angle-right`)
