### ISSUE TITLE
Issue with planetary response network

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#144]
Going to this page breaks the header.

**Comment by noahmalmed** [comment]
Waiting on design decision from @beckyrother

**Comment by beckyrother** [comment]
@noahmalmed the best solution would be to truncate the name of the project to the number of characters that comfortably fit in the header + `...`, so `planetary response ne...` or whatever fits. 

it would be great to do this with every project, including native mobile projects, so that navigation stays consistent.
