### ISSUE TITLE
Android Drawing Annotation Scaling Bug

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#359]
**What the app is supposed to do:** Calculate width and height of subject image in order to determine scaling from client to natural (original) image coordinate systems in the case of drawing tasks.

**What the app does instead:** For OS=Android, the app uses a fixed pair of default width and height values, which results in incorrect coordinates for the box annotations that are saved as part of submitted classifications.  This bug is related to changes made to [DrawingClassifier.js](https://github.com/zooniverse/mobile/blob/master/src/components/Markings/DrawingClassifier.js) in #336 and #345 that now (effective since release v2.8.2) sets fixed default values for natural width and height.

For full details on bug, please see the [Incident Doc](https://docs.google.com/document/d/1KVqJi0IF3FERsn5RGvN2_o3pZDG5rN5cZtblxasaEWw/edit?usp=sharing) in the Zooniverse Drive (team access only).

**Exact steps to Reproduce:** On the mobile test project on staging ([project link](https://master.pfe-preview.zooniverse.org/projects/chelseatroy/project-with-all-mobile-workflow-types), [lab link](https://master.pfe-preview.zooniverse.org/lab/1892)) I created a test subject set [link](https://master.pfe-preview.zooniverse.org/lab/1892/subject-sets/4828) that has 3 identical subjects with known `naturalWidth`=1760 and `naturalHeight`=2718.  I can see that subject_dimensions in classification metadata are correctly reported (by viewing network traffic via browser dev tools).  I am not able to reproduce the bug behavior on my own due to lack of Android phone or emulator.

**Possible Solution:** Although the OS=Android case was treated separately in #336 and #345 specifically due to failures of `Image.getSize()` to work properly, and I found a few other examples via Googling that others on RN 0.60 (and even higher) are running into the same issue, there may be an possible solution: it might be possible to use `Image.resolveAssetSource()` instead -- see https://github.com/DylanVann/react-native-fast-image/issues/461#issuecomment-501858443

**Comment by chelseatroy** [comment]
Spend some time looking into this this morning.

Indeed, we ran into this issue on Android where `Image.getSize()` doesn't work. The thing about [this solution](https://github.com/DylanVann/react-native-fast-image/issues/461#issuecomment-501858443) is it's correcting a different issue than the one we have. Namely, that solution is for `Image.getSize()` not working on a local image (one not fetched from a server). Our issue is that `Image.getSize()` isn't even working on Android for images fetched from a server. So I'm actually somewhat certain that that thread misdiagnoses the problem. The fact that the OP included sample code, rather than tested code, and the fact that most of the commenters after the OP are saying "same issue" instead of "thanks, this worked!" are both supporting evidence for that hypothesis unfortunately.

That said, @lcjohnso , did you say that there is a way to manually fix the data? It may be possible for me in the mobile app to manually adjust the metadata before sending it back to the server to resolve the issue while maintaining our temporary fix to get the images to display at a reasonable size and shape on Android.
