### ISSUE TITLE
Add Notifications page

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/mobile#481]
This page will improve UX by allowing our volunteers to reread missed notifications. It also provides a viable landing page option. Final design TBD.

<img width="300" alt="Screen Shot 2023-11-10 at 3 35 03 PM" src="https://github.com/zooniverse/mobile/assets/89043489/00a162ba-d483-4c00-9126-8a26021f4e14">

User story: 
As a volunteer,
When I click the notifications button
The app should show me my most current notification
So that I can reread the message.

**Comment by lcjohnso** [comment]
I propose this notifications page be accessed via the hamburger menu rather than a bottom nav bar. See relevant discussion re: homepage/projects page redesign/separation in #482 

Regarding content on this page:
1. **Default View**: Does this page look OK in the case of no notifications?
2. **Combine Notifications and Landing Page?**: Is it possible that this notifications page could act as the landing page? It seems the only addition needed to this page's design would be a "classify now" button tied to the top notification, and that we think it is OK to display the past notifications  at the bottom of the page that volunteers would access when the click on a notification.
3. **Top Display & Past Notifications**: Should the notification page display the most recent notification in full at top by default, followed by the full list of notifications at the bottom? And then swap in other notifications into the top display position in the case that one of the past notifications is selected?

**Comment by lcjohnso** [comment]
Closed by #498
