### ISSUE TITLE
notification settings available when not logged in

### ISSUE THREAD

**Issue by camallen** [zooniverse/mobile#81]
i can see my previous login notification settings when i'm not logged in.

**Comment by robinschaaf** [comment]
This is actually by design, since notification settings are at a device level rather than user level.  We made a decision a month or so ago to set the user notification settings to the mobile-friendly projects, rather than the users' projects since we'll only be sending notifications about mobile-friendly projects.  Hopefully that makes sense - perhaps there should be some wording added on that screen to explain this - that just because you log out doesn't mean you won't get the notifications any more.

**Comment by camallen** [comment]
yeah that totally does now as it's an app. I guess i was seeing that i was logged out and saw it said send me updates, etc in the wording so though emails (mostly as i know how we work). Could have said to this device or some such but i'm not worried so much. 

thanks for clarifying.
